### ISSUE TITLE
Test Failing with `undefined symbol: omp_set_dynamic` on Ubuntu Builds

### ISSUE THREAD

**Issue by prashnts** [PrashntS/pancake#3]
Latest travis tests fail with `undefined symbol: omp_set_dynamic`.

With `gcc`, `fopenmp` flag is required, however it is different within different compilers.

Ref: http://stackoverflow.com/questions/9685377/undefined-reference-to-omp-get-max-threads

@devkhan or @pragyajaiswal could you try and reproduce? It builds and passes tests just fine on OSX.

**Comment by prashnts** [comment]
Nevermind. Fixed in 8788c05b1ef22b6176ba7fc97df57275cf2b5a60.

**Comment by devkhan** [comment]
Yeah, sure, like we were able to build it successfully before. -_-

**Comment by prashnts** [comment]
Haha, @devkhan I think you'll find this Related #1. :p
