### ISSUE TITLE
source to downlaod viennarna in docs is incorrect

### ISSUE THREAD

**Issue by infinite-Joy** [PrashntS/pancake#6]
I could not download the source file for viennarna listed in the docs
http://metarna.readthedocs.io/en/latest/installation.html#pre-requisite

I guess the resource is not available. For resolution I would suggest using the below command
`wget http://www.tbi.univie.ac.at/RNA/download/sourcecode/2_2_x/ViennaRNA-2.2.10.tar.gz`
which I think is the most recent stable version.

**Comment by prashnts** [comment]
Thanks! `Vienna RNA` has had a habit of not maintaining permanent links to their source. 😬

I will update the docs with this link. In any case, I keep an archive [here](https://noop.pw/etc/vienna224.tar.gz) which is always accessible.
