### ISSUE TITLE
Add Python 3.6 support

### ISSUE THREAD

**Issue by bluesurfer** [PrashntS/pancake#9]

**Comment by prashnts** [comment]
Hi, could you please share a little more detail about what breaks in Python 3.6? Thanks!

**Comment by bluesurfer** [comment]
@prashnts 

If I run `pip install metarna` it said that `metarna` does not support python 3.6 invalidating the installation.

**Comment by prashnts** [comment]
I've released v4.0.5 which should fix this. Please could you check?
